kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeserve
spec:
 replicas: 3
 minReadySeconds: 10 
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavilable: 1
   minSurge: 1
selector:
 matchLabels:
  app: kubeserve
template:
 metadata:
  name: kubeserve
  labels:
   app: kubeserve
 spec:
 containers:
  - name: app
    image: leaddevops/kubeserve:v1
---
kind: Service
appVersion: v1
metadata:
 name: kubeserve
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
 selector:
  app: kubeserve
 
