apiVersion: v1
kind: Service
metadata:
 name: mysvc
spec:
 type: NodePort
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30009
 selector:
<<<<<<< HEAD
  type: webserver
=======
  type: webserver
>>>>>>> ccc3217751affa02ea0a34daf3426fb76bc9fb48
